### ISSUE TITLE
[windows] Stuck on 'preparing to download OS'

### ISSUE THREAD

**Issue by pazdera** [KanoComputing/kano-burners#61]
Someone on Twitter reported that he burners are consistently getting stuck during this phase.

![burner](https://cloud.githubusercontent.com/assets/169328/8954646/f904a64c-35de-11e5-88f6-a38229107ae6.jpg)

**Comment by raelity** [comment]
Hello. I've just experienced the same thing on OS X.

**Comment by Ealdwulf** [comment]
We've released a new version of the burners which give the option to upload a log to us if anything went wrong, to help us debug it. It would be great if you could have another go with that: http://downloads.kano.me/public/burners/kano-burner-osx.zip

**Comment by chleggett** [comment]
I am still having the same trouble on OS X with what I think is the newest burner (v3).

I launched the app within a terminal session and this is what I see:

    cleggett@mario MacOS % pwd
    ~/Desktop/Kano Burner.app/Contents/MacOS
    /Users/cleggett/Desktop/Kano Burner.app/Contents/MacOS
    cleggett@mario MacOS % sudo ./Kano\ Burner
    ~/Desktop/Kano Burner.app/Contents/MacOS
    2015-10-24 04:35:49.513 Kano Burner[52624:1480182] modalSession has been exited
    prematurely - check for a reentrant call to endModalSession:
     
    10/24 04:35:51 [ERROR] IPv4 RPC: failed to bind TCP port 5900
    Exception: [SocketCore.cc:293] errorCode=1 Failed to bind a socket, cause:
    Address already in use
     
    10/24 04:35:51 [ERROR] IPv6 RPC: failed to bind TCP port 5900
    Exception: [SocketCore.cc:293] errorCode=1 Failed to bind a socket, cause:
    Address already in use
     
    10/24 04:35:51 [ERROR] Exception caught
    Exception: [DownloadEngineFactory.cc:215] errorCode=1 Failed to setup RPC
    server.
    Traceback (most recent call last):
      File "<string>", line 283, in run
      File "../app/Kano Burner/build/Kano Burner/out00-PYZ.pyz/src.common.download",
    line 100, in download_kano_os
      File "../app/Kano Burner/build/Kano
    Burner/out00-PYZ.pyz/src.common.aria2_downloader", line 124, in isFinished
    AttributeError: 'NoneType' object has no attribute 'returncode'

**Comment by Ealdwulf** [comment]
Thanks, that's really useful!
v3 is the newest burner.
So we need to retry with different port numbers, and probably also capture
the ouput of aria2 in logs in case there are other errors.

**Comment by chleggett** [comment]
For convenience, here's the offending line:

https://github.com/KanoComputing/kano-burners/blob/6a4df1fa1c262ee2c206ce53446ab1395b8991de/src/common/aria2_downloader.py#L67

**Comment by g-guth** [comment]
I have the same problem on windows.

**Comment by chleggett** [comment]
@g-guth if you have VNC installed, disable it before running the burner.
